purchases-web/src/main/java/br/com/fic/purchases/controller/FornecedorMB.java
package br.com.fic.purchases.controller;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.ConversationScoped;
import javax.faces.bean.ManagedBean;

import br.com.fic.purchases.business.FornecedorBusinessLocal;
import br.com.fic.purchases.model.Fornecedor;

@ManagedBean
@ConversationScoped
public class FornecedorMB implements Serializable{

	private static final long serialVersionUID = 6340580511975270569L;

	private Fornecedor fornecedorSelecionado = new Fornecedor();
	
	@EJB(name="FornecedorBusiness")
	private FornecedorBusinessLocal fornecedorBusiness;
	
	public void salvar() {
		fornecedorBusiness.salvarFornecedor(fornecedorSelecionado);
		this.fornecedorSelecionado = new Fornecedor();
	}
	
	public List<Fornecedor> getFornecedores() {
		return fornecedorBusiness.selecionarFornecedores();
	}
	

	public Fornecedor getFornecedorSelecionado() {
		return fornecedorSelecionado;
	}

	public void setFornecedorSelecionado(Fornecedor fornecedorSelecionado) {
		this.fornecedorSelecionado = fornecedorSelecionado;
	}
	
	
}

purchases-web/src/main/java/br/com/fic/purchases/controller/PedidoMB.java
package br.com.fic.purchases.controller;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ValueChangeEvent;

import br.com.fic.purchases.business.FornecedorBusinessLocal;
import br.com.fic.purchases.business.ProdutoFornecedorBusinessLocal;
import br.com.fic.purchases.model.Fornecedor;
import br.com.fic.purchases.model.ItemPedido;
import br.com.fic.purchases.model.Produto;
import br.com.fic.purchases.model.ProdutoFornecedor;

@ManagedBean
@ViewScoped
public class PedidoMB implements Serializable {
	private static final long serialVersionUID = -4704559401429631194L;

	private ProdutoFornecedor produtoFornecedorSelecionado = new ProdutoFornecedor();
	private Fornecedor fornecedorSelecionado = new Fornecedor();
	private List<ProdutoFornecedor> produtoPorFornecedor = new ArrayList<ProdutoFornecedor>();
	private BigDecimal precoProdudo;
	

	private ItemPedido item = new ItemPedido();
	private List<ItemPedido> itens = new ArrayList<ItemPedido>();

	@EJB
	private FornecedorBusinessLocal fornecedorBusiness;
	@EJB
	private ProdutoFornecedorBusinessLocal produtoFornecedorBusiness;

	public void adcionarItem() {
		this.itens.add(item);
	}

	public void loadProdutoPorFornecedor(ValueChangeEvent evt) {
		System.out.println("Loading...");
		if (evt.getNewValue() != null) {
			Fornecedor consultaFornecedor = new Fornecedor();
			consultaFornecedor.setId(Long.valueOf(evt.getNewValue().toString()));
			this.produtoPorFornecedor = produtoFornecedorBusiness.selecionarProdutoPorFornecedor(consultaFornecedor);
		} else {
			System.out.println("Iniciando a lista de produtos");
			this.produtoPorFornecedor = new ArrayList<ProdutoFornecedor>();
		}
		System.out.println("Iniciando o preço do produto");
		this.precoProdudo = null;
		
	}
	
	public void loadPrecoProduto(ValueChangeEvent evt) {
		System.out.println("Carregando Preço");
		if(evt.getNewValue() != null){
			Produto produto = new Produto();
			produto.setId(Long.valueOf(evt.getNewValue().toString()));
			this.precoProdudo = produtoFornecedorBusiness.carregarPrecoProduto(produto);
			
		}
	}

	// GETS AND SETS
	public ProdutoFornecedor getProdutoFornecedorSelecionado() {
		return produtoFornecedorSelecionado;
	}

	public void setProdutoFornecedorSelecionado(
			ProdutoFornecedor produtoFornecedorSelecionado) {
		this.produtoFornecedorSelecionado = produtoFornecedorSelecionado;
	}

	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	public List<Fornecedor> getFornecedores() {
		return fornecedorBusiness.selecionarFornecedores();
	}

	public List<ProdutoFornecedor> getProdutoPorFornecedor() {
		return produtoPorFornecedor;
	}

	public void setProdutoPorFornecedor(
			List<ProdutoFornecedor> produtoPorFornecedor) {
		this.produtoPorFornecedor = produtoPorFornecedor;
	}
	
	public Fornecedor getFornecedorSelecionado() {
		return fornecedorSelecionado;
	}
	
	public void setFornecedorSelecionado(Fornecedor fornecedorSelecionado) {
		this.fornecedorSelecionado = fornecedorSelecionado;
	}
	
	public BigDecimal getPrecoProdudo() {
		return precoProdudo;
	}
	
	public void setPrecoProdudo(BigDecimal precoProdudo) {
		this.precoProdudo = precoProdudo;
	}
}

purchases-web/src/main/java/br/com/fic/purchases/controller/ProdutoMB.java
package br.com.fic.purchases.controller;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.ConversationScoped;
import javax.faces.bean.ManagedBean;

import br.com.fic.purchases.business.FornecedorBusinessLocal;
import br.com.fic.purchases.business.ProdutoFornecedorBusinessLocal;
import br.com.fic.purchases.model.Fornecedor;
import br.com.fic.purchases.model.Produto;
import br.com.fic.purchases.model.ProdutoFornecedor;

@ManagedBean
@ConversationScoped
public class ProdutoMB implements Serializable {
	private static final long serialVersionUID = -7802073407907474795L;

	private ProdutoFornecedor produtoFornecedorSelecionado = new ProdutoFornecedor();
	private Fornecedor fornecedorSelecionado = new Fornecedor();
	private Produto produtoSelecionado = new Produto();

	@EJB
	private FornecedorBusinessLocal fornecedorBusiness;

	@EJB
	private ProdutoFornecedorBusinessLocal produtoFornecedorBusiness;
	

	public void salvar() {
		this.produtoFornecedorSelecionado.setProduto(produtoSelecionado);
		produtoFornecedorBusiness.salvarProdutoFornecedor(produtoFornecedorSelecionado, fornecedorSelecionado);
		this.produtoSelecionado = new Produto();
		this.fornecedorSelecionado = new Fornecedor();
		this.produtoFornecedorSelecionado = new ProdutoFornecedor();
	}

	
	public List<Fornecedor> getFornecedores() {
		return fornecedorBusiness.selecionarFornecedores();
	}
	
	public List<ProdutoFornecedor> getProdutosFornecedores() {
		return produtoFornecedorBusiness.selecionarProdutosFornecedores();
	}
	
	
	//GETS and SETS
	public Fornecedor getFornecedorSelecionado() {
		return fornecedorSelecionado;
	}
	
	public void setFornecedorSelecionado(Fornecedor fornecedorSelecionado) {
		this.fornecedorSelecionado = fornecedorSelecionado;
	}

	public Produto getProdutoSelecionado() {
		return produtoSelecionado;
	}

	public void setProdutoSelecionado(Produto produtoSelecionado) {
		this.produtoSelecionado = produtoSelecionado;
	}


	public ProdutoFornecedor getProdutoFornecedorSelecionado() {
		return produtoFornecedorSelecionado;
	}
	
	public void setProdutoFornecedorSelecionado(ProdutoFornecedor produtoFornecedorSelecionado) {
		this.produtoFornecedorSelecionado = produtoFornecedorSelecionado;
	}

}

purchases-web/src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>FIC - Purchases</title>
	<link href="imagens/favicon1.ico" rel="shortcut icon" type="image/x-icon"/>
	
</h:head>
<body>
	<div id="header">
		<img src="imagens/logo.jpg" alt="FIC logo" />
		<ui:insert name="title">
			Título da Página
		</ui:insert>
		<h:link value="Fornecedor" outcome="cadastroFornecedor" />
		&nbsp;
		<h:link value="Produto" outcome="cadastroProduto" />
		&nbsp;
		<h:link value="Pedido" outcome="cadastroPedido" />
		&nbsp;
		<hr />
	</div>
	<ui:insert name="conteudo">
		Espaço para o conteúdo
	</ui:insert>
	<hr />
	<div id="footer" style="text-align: center">&copy; 2015 FIC -
		Frameworks. Todos os direitos reservados.</div>
</body>
</html>

purchases-web/src/main/webapp/cadastroFornecedor.xhtml
<ui:composition
		template="/WEB-INF/templates/template.xhtml"
		xmlns="http://www.w3.org/1999/xhtml"
     	xmlns:h="http://java.sun.com/jsf/html"
      	xmlns:f="http://java.sun.com/jsf/core"
      	xmlns:ui="http://java.sun.com/jsf/facelets">
      	
   <ui:define name="title">
   		<h1 style="text-align: left;">Cadastro de Fornecedor</h1>
   	</ui:define>
      	
   <ui:define name="conteudo">
   		<h:form >
   			<h:panelGrid columns="3">
   				<h:outputLabel value="Nome: " for="nome" />
   				<h:inputText value="#{fornecedorMB.fornecedorSelecionado.nome}" id="nome"  required="true" />
   				<h:message for="nome"/>
   				
   				<h:outputLabel value="E-mail: " for="email" />
  				<h:inputText value="#{fornecedorMB.fornecedorSelecionado.email}" id="email" required="true"/>
  				<h:message for="email"/>
  				<h:panelGroup>
  					<h:commandButton action="#{fornecedorMB.salvar()}" value="Salvar" />
  				</h:panelGroup> 				
   			</h:panelGrid>
   		</h:form>
   		<br/>
   		<h:dataTable rendered="#{not empty fornecedorMB.fornecedores}" 
   				value="#{fornecedorMB.fornecedores}" var="forne">
   			<h:column>
   				<f:facet name="header">CÓDIGO</f:facet>
   				 #{forne.id}
   			</h:column>
   			<h:column>
   				<f:facet name="header">NOME</f:facet>
   				 #{forne.nome}
   			</h:column>
   			<h:column>
   				<f:facet name="header">E-MAIL</f:facet>
   				 #{forne.email}
   			</h:column>
   		</h:dataTable>
   </ui:define>
</ui:composition>

purchases-web/src/main/webapp/cadastroPedido.xhtml
<ui:composition template="/WEB-INF/templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<ui:define name="title">
		<h1 style="text-align: left;">Cadastro de Pedido</h1>
	</ui:define>

	<ui:define name="conteudo">
		<h:form>
			<h:panelGrid columns="4">
				<h:outputLabel value="FORNECEDOR " for="cdFornecedor" />
				<h:outputLabel value="PRODUTO " for="cdProduto" />
				<h:outputLabel value="PREÇO R$ " for="preco"/>
				<h:outputLabel value="QUANTIDADE " for="quantidade"/>
				
				<h:selectOneMenu id="cdFornecedor" valueChangeListener="#{pedidoMB.loadProdutoPorFornecedor}">
					<f:selectItem value="#{null}" itemLabel="--- Selecione ---"/>
					<f:selectItems 
						value="#{pedidoMB.fornecedores}"
						var="item"
						itemLabel="#{item.nome}"
						itemValue="#{item.id}" />
					<f:ajax render="cdProduto precoProduto"/>
				</h:selectOneMenu>
				
				<h:selectOneMenu id="cdProduto" valueChangeListener="#{pedidoMB.loadPrecoProduto}">
					<f:selectItem value="#{null}" itemLabel="--- Selecione ---"/>
					<f:selectItems 
						value="#{pedidoMB.produtoPorFornecedor}"
						var="item"
						itemLabel="#{item.produto.descricao}"
						itemValue="#{item.produto.id}"
					/>
					<f:ajax render="precoProduto"/>
				</h:selectOneMenu>
				
				<h:inputText id="precoProduto" value="#{pedidoMB.precoProdudo}" disabled="true" style="color: red;"/>
				<h:inputText id="quantidade" value="" />


			</h:panelGrid>
		</h:form>
		<br />

	</ui:define>
</ui:composition>

purchases-web/src/main/webapp/cadastroProduto.xhtml
<ui:composition
		template="/WEB-INF/templates/template.xhtml"
		xmlns="http://www.w3.org/1999/xhtml"
     	xmlns:h="http://java.sun.com/jsf/html"
      	xmlns:f="http://java.sun.com/jsf/core"
      	xmlns:ui="http://java.sun.com/jsf/facelets">
      	
   <ui:define name="title">
   		<h1 style="text-align: left;">Cadastro de Produto</h1>
   	</ui:define>
      	
   <ui:define name="conteudo">
   		<h:form >
   			<h:panelGrid columns="3">
   				<h:outputLabel value="Código: " for="codigo" />
   				<h:inputText value="#{produtoMB.produtoSelecionado.codigo}" id="codigo" required="true" />
   				<h:message for="codigo"/>
   				
   				<h:outputLabel value="Descrição: " for="descricao" />
  				<h:inputText value="#{produtoMB.produtoSelecionado.descricao}" id="descricao" required="true"/>
  				<h:message for="descricao"/>
  				
  				<h:outputLabel value="Unidade Médida: " for="unidade"/>
  				<h:inputText value="#{produtoMB.produtoSelecionado.unidadeMedida}" id="unidade" required="true"/>
  				<h:message for="unidade"/>
  				
  				<h:outputLabel value="Preço R$ " for="preco"/>
  				<h:inputText value="#{produtoMB.produtoFornecedorSelecionado.precoUnitario}" id="preco">
  					<f:convertNumber currencySymbol="R$" type="currency" />
  				</h:inputText>
  				<h:message for="preco"/>
  				
  				<h:outputLabel value="Fornecedor: " for="fornecedor"/>
  				<h:selectOneMenu id="fornecedor" value="#{produtoMB.fornecedorSelecionado.id}">
  				<f:selectItem itemValue="#{null}" itemLabel="--- Selecione ---"/>
  					<f:selectItems
  						value="#{produtoMB.fornecedores}"
  						var="forne"
  						itemLabel="#{forne.nome}"
  						itemValue="#{forne.id}">
  						
  					</f:selectItems>
  				</h:selectOneMenu>
  				<h:message for="fornecedor"/>
  				<h:panelGroup>
  					<h:commandButton action="#{produtoMB.salvar()}" value="Salvar"/>
  				</h:panelGroup> 				
   			</h:panelGrid>
   		</h:form>
   		<br/>
   		<h:dataTable value="#{produtoMB.produtosFornecedores}" var="item" rendered="#{not empty produtoMB.produtosFornecedores}">
   			<h:column>
   				<f:facet name="header">CÓDIGO</f:facet>
   				#{item.produto.codigo}
   			</h:column>
   			<h:column>
   				<f:facet name="header">PROODUTO</f:facet>
   				#{item.produto.descricao}
   			</h:column>
   			<h:column>
   				<f:facet name="header">FORNECEDOR</f:facet>
   				#{item.fornecedor.nome}
   			</h:column>
   			<h:column>
   				<f:facet name="header">UNIDADE</f:facet>
   				#{item.produto.unidadeMedida}
   			</h:column>
   			<h:column>
   				<f:facet name="header">PRECO R$</f:facet>
   				#{item.precoUnitario}
   			</h:column>
   		</h:dataTable>
   		
   </ui:define>
</ui:composition>